services:
  - type: web
    name: wiki-platform
    env: node
    plan: free
    buildCommand: npm install && npm run build && node build-fix.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: false